name: CI

on: [push, pull_request]

jobs:
  build-php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1"]
        service: ["php-fpm", "php-worker", "workspace"]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        PHP_VERSION: ${{ matrix.php_version }}
        BUILD_SERVICE: ${{ matrix.service }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      run: bash build-image.sh
  build-mysql:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql_version: ["5.7", "8.0"]
        service: ["mysql"]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        MYSQL_VERSION: ${{ matrix.mysql_version }}
        BUILD_SERVICE: ${{ matrix.service }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      run: bash build-image.sh
  build-redis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["redis"]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        BUILD_SERVICE: ${{ matrix.service }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      run: bash build-image.sh
  build-elasticsearch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["elasticsearch"]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        BUILD_SERVICE: ${{ matrix.service }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      run: bash build-image.sh
  build-mongoDB:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["mongo"]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          BUILD_SERVICE: ${{ matrix.service }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        run: bash build-image.sh
